import { useState, useEffect, useRef, useCallback } from 'react'
import { useParams, useSearchParams, Link, useNavigate } from 'react-router-dom'
import { isSubscribed, toggleSubscription, createPlaylistWithVideos } from '../lib/library'
import SmartImage from '../components/SmartImage'
import { buildVideoThumbnailUrl, transformImageUrl } from '../lib/imagePreferences'
import './Channel.css'

type Tab = 'home' | 'videos' | 'latest' | 'shorts' | 'streams' | 'playlists' | 'community' | 'search'

interface ChannelInfo {
  author: string
  authorId: string
  authorUrl?: string
  authorBanners?: Array<{ url: string; width: number; height: number }>
  authorThumbnails?: Array<{ url: string; width: number; height: number }>
  authorVerified?: boolean
  subCount?: number
  totalViews?: number
  joined?: number
  description?: string
  autoGenerated?: boolean
}

interface VideoItem {
  videoId: string
  title: string
  author?: string
  authorId?: string
  authorThumbnails?: Array<{ url: string; width: number; height: number }>
  viewCount?: number
  viewCountText?: string
  published?: number
  publishedText?: string
  lengthSeconds?: number
  liveNow?: boolean
  is4k?: boolean
  isVr360?: boolean
  hasCaptions?: boolean
}

interface PlaylistItem {
  playlistId: string
  title: string
  playlistThumbnail?: string
  videoCount?: number
  videos?: Array<{ videoId: string }>
}

interface HomeVideoItem {
  type: 'video'
  videoId: string
  title: string
  author?: string
  authorId?: string | null
  durationText?: string
  durationSeconds?: number | null
  viewCountText?: string
  publishedText?: string
  thumbnailUrl?: string | null
  isLive?: boolean
}

interface HomeChannelItem {
  type: 'channel'
  channelId: string
  name: string
  thumbnailUrl?: string | null
  subscribers?: string
  videoCount?: string
}

interface HomePlaylistItem {
  type: 'playlist'
  playlistId: string
  title: string
  thumbnailUrl?: string | null
}

type HomeShelfItem = HomeVideoItem | HomeChannelItem | HomePlaylistItem

interface HomeShelf {
  title: string
  items: HomeShelfItem[]
  playlistId?: string | null
  playAllVideoId?: string | null
}

interface HomeFeaturedVideo {
  videoId: string
  title: string
  description?: string
  viewCountText?: string
  publishedText?: string
}

interface ChannelHomeData {
  featuredVideo: HomeFeaturedVideo | null
  shelves: HomeShelf[]
}

interface CommunityPost {
  id?: string
  author?: string
  authorThumbnails?: Array<{ url: string; width: number; height: number }>
  content?: string
  contentHtml?: string
  publishedText?: string
  likeCount?: number
}

function wsrv(url: string, w?: number): string {
  return transformImageUrl(url, undefined, w)
}

function getThumbnailUrl(videoId: string): string {
  return buildVideoThumbnailUrl(videoId, 'mqdefault.jpg')
}

function getBestThumbnail(thumbs?: Array<{ url: string; width: number; height: number }>): string {
  if (!thumbs || !thumbs.length) return ''
  const sorted = [...thumbs].sort((a, b) => (b.width || 0) - (a.width || 0))
  const best = sorted.find(t => (t.width || 0) >= 88) || sorted[0]
  return wsrv(best.url, 88)
}

function getBannerUrl(banners?: Array<{ url: string; width: number; height: number }>): string {
  if (!banners || !banners.length) return ''
  const best = banners.reduce((a, b) => ((b.width || 0) > (a.width || 0) ? b : a), banners[0])
  return wsrv(best.url, 1400)
}

function formatSubs(n?: number): string {
  if (!n) return ''
  if (n >= 100000000) return `${(n / 100000000).toFixed(1)}億人`
  if (n >= 10000) return `${Math.floor(n / 10000)}万人`
  return `${n.toLocaleString()}人`
}

function formatViews(n?: number): string {
  if (!n) return ''
  if (n >= 100000000) return `${(n / 100000000).toFixed(1)}億回視聴`
  if (n >= 10000) return `${Math.floor(n / 10000)}万回視聴`
  return `${n.toLocaleString()}回視聴`
}

function formatDuration(seconds?: number): string {
  if (!seconds || seconds < 0) return ''
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = seconds % 60
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
  return `${m}:${String(s).padStart(2, '0')}`
}

function SkeletonCard() {
  return (
    <div className="skeleton-card">
      <div className="skeleton-thumb" />
      <div className="skeleton-info">
        <div className="skeleton-line skeleton-title" />
        <div className="skeleton-line skeleton-title-short" />
        <div className="skeleton-channel-row">
          <div className="skeleton-avatar" />
          <div className="skeleton-line skeleton-channel" />
        </div>
        <div className="skeleton-line skeleton-views" />
      </div>
    </div>
  )
}

function VideoCard({ video }: { video: VideoItem }) {
  const navigate = useNavigate()
  const thumb = getThumbnailUrl(video.videoId)
  const duration = formatDuration(video.lengthSeconds)
  const views = formatViews(video.viewCount)
  const channelIcon = getBestThumbnail(video.authorThumbnails)
  const channelUrl = video.authorId ? `/channel/${video.authorId}` : null

  const badges: string[] = []
  if (video.liveNow) badges.push('LIVE')
  if (video.is4k) badges.push('4K')
  if (video.isVr360) badges.push('360°')
  if (video.hasCaptions) badges.push('CC')

  return (
    <Link to={`/watch/${video.videoId}`} className="ch-video-card">
      <div className="thumb-wrap">
        <SmartImage
          className="thumb-img"
          src={thumb}
          fallbackSrc={buildVideoThumbnailUrl(video.videoId)}
          proxyWidth={480}
          alt={video.title}
          loading="lazy"
          onLoad={e => (e.currentTarget as HTMLImageElement).classList.add('loaded')}
        />
        {duration && <span className="duration-badge">{duration}</span>}
        {badges.length > 0 && (
          <div className="thumb-badges">
            {badges.map(b => (
              <span key={b} className={b === 'LIVE' ? 'badge-live' : 'badge-tag'}>{b}</span>
            ))}
          </div>
        )}
      </div>
      <div className="card-info">
        <div className="card-title">{video.title}</div>
        <div className="card-meta">
          <div className="card-channel-row">
            {channelIcon
              ? <SmartImage className="channel-icon" src={channelIcon} alt={video.author || ''} loading="lazy" proxyWidth={88} />
              : <div className="channel-icon-placeholder" />
            }
            {channelUrl
              ? <span
                  className="card-channel card-channel-link"
                  onClick={e => { e.preventDefault(); e.stopPropagation(); navigate(channelUrl) }}
                >{video.author || ''}</span>
              : <span className="card-channel">{video.author || ''}</span>
            }
          </div>
          <div className="card-stats">
            {views && <span>{views}</span>}
            {video.publishedText && <span>{video.publishedText}</span>}
          </div>
        </div>
      </div>
    </Link>
  )
}

function PlaylistCard({ item }: { item: PlaylistItem }) {
  const thumb = item.playlistThumbnail
    ? wsrv(item.playlistThumbnail, 480)
    : (item.videos && item.videos[0]?.videoId ? getThumbnailUrl(item.videos[0].videoId) : '')

  return (
    <Link to={`/playlist/${item.playlistId}`} className="ch-video-card">
      <div className="thumb-wrap playlist-thumb-wrap">
        {thumb && <SmartImage className="thumb-img" src={thumb} alt={item.title} loading="lazy" proxyWidth={480} onLoad={e => (e.currentTarget as HTMLImageElement).classList.add('loaded')} />}
        <div className="playlist-count-badge">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="12" height="12">
            <line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/>
            <line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/>
          </svg>
          {item.videoCount != null ? `${item.videoCount}本` : '再生リスト'}
        </div>
      </div>
      <div className="card-info">
        <div className="card-title">{item.title || ''}</div>
        {item.videoCount != null && (
          <div className="card-meta"><span style={{ fontSize: '0.8rem', color: 'var(--muted)' }}>{item.videoCount}本の動画</span></div>
        )}
      </div>
    </Link>
  )
}

function CommunityPostCard({ post }: { post: CommunityPost }) {
  const [expanded, setExpanded] = useState(false)
  const authorIcon = getBestThumbnail(post.authorThumbnails)
  const content = post.content || (post.contentHtml?.replace(/<[^>]*>/g, '') || '')
  const likes = post.likeCount != null ? Number(post.likeCount).toLocaleString() : null
  const needsToggle = content.length > 200 || content.split('\n').length > 4

  return (
    <div className="community-post">
      <div className="community-post-author">
        {authorIcon
          ? <SmartImage className="community-post-avatar loaded" src={authorIcon} alt="" loading="lazy" proxyWidth={88} />
          : <div className="community-avatar-placeholder" />
        }
        <div className="community-author-info">
          <div className="community-author-name">{post.author || ''}</div>
          {post.publishedText && <div className="community-post-date">{post.publishedText}</div>}
        </div>
      </div>
      <div className={`community-post-content${expanded ? ' expanded' : ''}`}>{content}</div>
      {needsToggle && (
        <button className="community-expand-btn" onClick={() => setExpanded(e => !e)}>
          {expanded ? '閉じる' : 'もっと見る'}
        </button>
      )}
      {likes != null && (
        <div className="community-likes">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="14" height="14">
            <path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3H14z"/>
            <path d="M7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"/>
          </svg>
          {likes}
        </div>
      )}
    </div>
  )
}

export default function Channel() {
  const { channelId: routeChannelId } = useParams<{ channelId: string }>()
  const [searchParams] = useSearchParams()
  const channelId = routeChannelId || searchParams.get('id') || ''
  const navigate = useNavigate()

  const [channelInfo, setChannelInfo] = useState<ChannelInfo | null>(null)
  const [heroLoading, setHeroLoading] = useState(true)
  const [heroError, setHeroError] = useState('')
  const [descExpanded, setDescExpanded] = useState(false)
  const [subscribed, setSubscribed] = useState(false)

  const [activeTab, setActiveTab] = useState<Tab>('home')
  const [sortBy, setSortBy] = useState('newest')
  const [searchQuery, setSearchQuery] = useState('')
  const [searchPage, setSearchPage] = useState(1)

  const [videos, setVideos] = useState<VideoItem[]>([])
  const [continuation, setContinuation] = useState<string | null>(null)
  const [contentLoading, setContentLoading] = useState(false)
  const [contentError, setContentError] = useState('')
  const [hasMore, setHasMore] = useState(false)
  const [loadingMore, setLoadingMore] = useState(false)

  const [playlists, setPlaylists] = useState<PlaylistItem[]>([])
  const [communityPosts, setCommunityPosts] = useState<CommunityPost[]>([])

  const [homeData, setHomeData] = useState<ChannelHomeData | null>(null)
  const [homeLoading, setHomeLoading] = useState(false)
  const [homeError, setHomeError] = useState('')
  const [featuredEduUrl, setFeaturedEduUrl] = useState<string | null>(null)

  const loadGenRef = useRef(0)

  useEffect(() => {
    if (!channelId) return
    setHeroLoading(true)
    setHeroError('')
    setChannelInfo(null)

    fetch(`/api/channels/${encodeURIComponent(channelId)}`)
      .then(r => r.json())
      .then(data => {
        if (data.error) throw new Error(data.error)
        setChannelInfo(data)
        setSubscribed(isSubscribed(data.authorId))
        document.title = `${data.author || 'チャンネル'} — Choco-Tube`
      })
      .catch(e => setHeroError(e.message))
      .finally(() => setHeroLoading(false))
  }, [channelId])

  const loadTab = useCallback(async (tab: Tab, reset: boolean, sort?: string, contToken?: string | null) => {
    if (!channelId) return
    const gen = ++loadGenRef.current
    const effectiveSort = sort ?? sortBy
    const effectiveCont = reset ? null : (contToken ?? continuation)

    if (reset) {
      setVideos([])
      setPlaylists([])
      setCommunityPosts([])
      setContinuation(null)
      setHasMore(false)
      setContentError('')
      setContentLoading(true)
    } else {
      setLoadingMore(true)
    }

    try {
      let items: VideoItem[] = []
      let newCont: string | null = null
      let plItems: PlaylistItem[] = []
      let commItems: CommunityPost[] = []

      if (tab === 'videos') {
        const p = new URLSearchParams({ sort_by: effectiveSort })
        if (effectiveCont) p.set('continuation', effectiveCont)
        const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/videos?${p}`).then(r => r.json())
        if (data.error) throw new Error(data.error)
        items = (data.videos || []).map((item: VideoItem) => (
          !item.authorThumbnails && channelInfo?.authorThumbnails
            ? { ...item, authorThumbnails: channelInfo.authorThumbnails }
            : item
        ))
        newCont = data.continuation || null

      } else if (tab === 'shorts') {
        const p = new URLSearchParams()
        if (effectiveCont) p.set('continuation', effectiveCont)
        const qs = p.toString() ? `?${p}` : ''
        const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/shorts${qs}`).then(r => r.json())
        if (data.error) throw new Error(data.error)
        items = (data.videos || []).map((item: VideoItem) => (
          !item.authorThumbnails && channelInfo?.authorThumbnails
            ? { ...item, authorThumbnails: channelInfo.authorThumbnails }
            : item
        ))
        newCont = data.continuation || null

      } else if (tab === 'streams') {
        const p = new URLSearchParams()
        if (effectiveCont) p.set('continuation', effectiveCont)
        const qs = p.toString() ? `?${p}` : ''
        const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/streams${qs}`).then(r => r.json())
        if (data.error) throw new Error(data.error)
        items = (data.videos || []).map((item: VideoItem) => (
          !item.authorThumbnails && channelInfo?.authorThumbnails
            ? { ...item, authorThumbnails: channelInfo.authorThumbnails }
            : item
        ))
        newCont = data.continuation || null

      } else if (tab === 'latest') {
        const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/latest`).then(r => r.json())
        if (data.error) throw new Error(data.error)
        items = (Array.isArray(data) ? data : (data.videos || [])).map((item: VideoItem) => (
          !item.authorThumbnails && channelInfo?.authorThumbnails
            ? { ...item, authorThumbnails: channelInfo.authorThumbnails }
            : item
        ))
        newCont = null

      } else if (tab === 'playlists') {
        const p = new URLSearchParams()
        if (effectiveCont) p.set('continuation', effectiveCont)
        const qs = p.toString() ? `?${p}` : ''
        const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/playlists${qs}`).then(r => r.json())
        if (data.error) throw new Error(data.error)
        plItems = data.playlists || []
        newCont = data.continuation || null

      } else if (tab === 'community') {
        const p = new URLSearchParams()
        if (effectiveCont) p.set('continuation', effectiveCont)
        const qs = p.toString() ? `?${p}` : ''
        const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/comments${qs}`).then(r => r.json())
        if (data.error) throw new Error(data.error)
        commItems = data.posts || data.comments || []
        newCont = data.continuation || null
      }

      if (gen !== loadGenRef.current) return

      if (reset) {
        setVideos(items)
        setPlaylists(plItems)
        setCommunityPosts(commItems)
      } else {
        setVideos(prev => [...prev, ...items])
        setPlaylists(prev => [...prev, ...plItems])
        setCommunityPosts(prev => [...prev, ...commItems])
      }
      setContinuation(newCont)
      setHasMore(!!newCont)

    } catch (e: unknown) {
      if (gen !== loadGenRef.current) return
      setContentError((e as Error).message)
    } finally {
      if (gen === loadGenRef.current) {
        setContentLoading(false)
        setLoadingMore(false)
      }
    }
  }, [channelId, sortBy, continuation, channelInfo?.authorThumbnails])

  const doSearch = useCallback(async (q: string, page: number, reset: boolean) => {
    if (!channelId || !q.trim()) return
    const gen = ++loadGenRef.current
    if (reset) {
      setVideos([])
      setContentLoading(true)
      setContentError('')
      setHasMore(false)
    } else {
      setLoadingMore(true)
    }
    try {
      const p = new URLSearchParams({ q: q.trim() })
      if (page > 1) p.set('page', String(page))
      const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/search?${p}`).then(r => r.json())
      if (data.error) throw new Error(data.error)
      if (gen !== loadGenRef.current) return
      const results: VideoItem[] = (data.results || data.videos || []).map((item: VideoItem) => (
        !item.authorThumbnails && channelInfo?.authorThumbnails
          ? { ...item, authorThumbnails: channelInfo.authorThumbnails }
          : item
      ))
      if (reset) setVideos(results)
      else setVideos(prev => [...prev, ...results])
      setHasMore(results.length >= 20)
    } catch (e: unknown) {
      if (gen === loadGenRef.current) setContentError((e as Error).message)
    } finally {
      if (gen === loadGenRef.current) { setContentLoading(false); setLoadingMore(false) }
    }
  }, [channelId, channelInfo?.authorThumbnails])

  useEffect(() => {
    if (!homeData?.featuredVideo?.videoId) return
    const vid = homeData.featuredVideo.videoId
    setFeaturedEduUrl(null)
    fetch('/api/edu/params/choco-1')
      .then(r => r.json())
      .then(json => {
        if (json.error) return
        let params: string = json.params || ''
        params = params
          .replace(/([?&])enablejsapi=[^&]*/g, '')
          .replace(/([?&])origin=[^&]*/g, '')
          .replace(/([?&])autoplay=[^&]*/g, '')
          .replace(/([?&])loop=[^&]*/g, '')
          .replace(/([?&])playlist=[^&]*/g, '')
          .replace(/\?&/g, '?')
          .replace(/&&+/g, '&')
          .replace(/[?&]$/, '')
        if (!params.includes('?') && params.includes('&')) {
          params = params.replace('&', '?')
        }
        const sep = params.includes('?') ? '&' : '?'
        const url = `https://www.youtubeeducation.com/embed/${vid}${params}${sep}autoplay=1&enablejsapi=1`
        setFeaturedEduUrl(url)
      })
      .catch(() => {})
  }, [homeData?.featuredVideo?.videoId])

  const loadHome = useCallback(async () => {
    if (!channelId) return
    setHomeLoading(true)
    setHomeError('')
    setHomeData(null)
    try {
      const data = await fetch(`/api/channels/${encodeURIComponent(channelId)}/home`).then(r => r.json())
      if (data.error) throw new Error(data.error)
      setHomeData(data)
    } catch (e: unknown) {
      setHomeError((e as Error).message)
    } finally {
      setHomeLoading(false)
    }
  }, [channelId])

  const switchTab = (tab: Tab) => {
    setActiveTab(tab)
    setSearchQuery('')
    setSearchPage(1)
    if (tab === 'home') {
      if (!homeData && !homeLoading) loadHome()
    } else if (tab !== 'search') {
      loadTab(tab, true, sortBy, null)
    }
  }

  useEffect(() => {
    if (channelId) {
      loadHome()
    }
  }, [channelId])

  const handleSortChange = (val: string) => {
    setSortBy(val)
    if (['videos', 'shorts', 'streams'].includes(activeTab)) {
      loadTab(activeTab, true, val, null)
    }
  }

  const handleSubBtn = () => {
    if (!channelInfo) return
    const result = toggleSubscription({
      authorId: channelInfo.authorId,
      author: channelInfo.author,
      authorThumbnails: channelInfo.authorThumbnails,
      subCount: channelInfo.subCount,
    })
    setSubscribed(result)
  }

  const playAllShelf = (shelf: HomeShelf) => {
    // YouTubeのフルプレイリストIDがある場合はプレイリストページへ遷移
    if (shelf.playlistId) {
      const videoItems = shelf.items.filter((item): item is HomeVideoItem => item.type === 'video')
      const firstVideoId = shelf.playAllVideoId || videoItems[0]?.videoId
      if (firstVideoId) {
        navigate(`/watch/${firstVideoId}?list=${encodeURIComponent(shelf.playlistId)}&index=0`)
      } else {
        navigate(`/playlist/${encodeURIComponent(shelf.playlistId)}`)
      }
      return
    }
    // フォールバック：表示中の動画でローカル再生リストを作成
    const videoItems = shelf.items.filter((item): item is HomeVideoItem => item.type === 'video')
    if (videoItems.length === 0) return
    const pl = createPlaylistWithVideos(shelf.title || '再生リスト', videoItems.map(v => ({
      videoId: v.videoId,
      title: v.title,
      author: v.author || channelInfo?.author || '',
      authorId: v.authorId || channelInfo?.authorId || '',
    })))
    navigate(`/watch/${videoItems[0].videoId}?localpl=${encodeURIComponent(pl.id)}&index=0`)
  }

  const bannerUrl = getBannerUrl(channelInfo?.authorBanners)
  const avatarUrl = channelInfo?.authorThumbnails
    ? (() => {
        const sorted = [...(channelInfo.authorThumbnails || [])].sort((a, b) => (b.width || 0) - (a.width || 0))
        const best = sorted.find(t => (t.width || 0) >= 88) || sorted[0]
        return best ? best.url : ''
      })()
    : ''

  const desc = channelInfo?.description || ''
  const descNeedsToggle = desc.length > 120 || desc.split('\n').length > 3

  const showSort = ['videos', 'shorts', 'streams'].includes(activeTab)
  const showSearch = activeTab === 'search'

  const isVideoTab = ['videos', 'latest', 'shorts', 'streams'].includes(activeTab)
  const noContent = !contentLoading && !contentError &&
    (isVideoTab ? videos.length === 0 : activeTab === 'playlists' ? playlists.length === 0 : communityPosts.length === 0)

  return (
    <div className="channel-page">
      {heroLoading ? (
        <div className="channel-hero-skeleton">
          <div className="skeleton-banner" />
          <div className="channel-info-wrap">
            <div className="channel-avatar-wrap">
              <div className="skeleton-avatar-lg" />
            </div>
            <div className="channel-meta">
              <div className="skeleton-line" style={{ width: 200, height: 20, marginBottom: 10, borderRadius: 6 }} />
              <div className="skeleton-line" style={{ width: 260, height: 13, marginBottom: 8, borderRadius: 5 }} />
              <div className="skeleton-line" style={{ width: 340, height: 12, borderRadius: 5 }} />
            </div>
          </div>
        </div>
      ) : heroError ? (
        <div className="error-state">
          <div className="error-icon">⚠️</div>
          <p>チャンネル情報の取得に失敗しました。</p>
        </div>
      ) : channelInfo ? (
        <div className="channel-hero">
          <div className="channel-banner-wrap">
            {bannerUrl
              ? <SmartImage className="channel-banner" src={bannerUrl} alt="" proxyWidth={1600} onLoad={e => (e.currentTarget as HTMLImageElement).classList.add('loaded')} onError={e => { (e.currentTarget as HTMLImageElement).style.display = 'none' }} />
              : null
            }
          </div>
          <div className="channel-info-wrap">
            <div className="channel-avatar-wrap">
              {avatarUrl && (
                <SmartImage
                  className="channel-avatar"
                  src={avatarUrl}
                  proxyWidth={176}
                  alt={channelInfo.author || ''}
                  onLoad={e => (e.currentTarget as HTMLImageElement).classList.add('loaded')}
                />
              )}
            </div>
            <div className="channel-meta">
              <h1 className="channel-name">
                {channelInfo.author || ''}
                {channelInfo.authorVerified && (
                  <span className="channel-verified" title="認証済み">✓</span>
                )}
              </h1>
              <div className="channel-sub-meta">
                {channelInfo.subCount != null && (
                  <span>登録者 {formatSubs(channelInfo.subCount)}</span>
                )}
                {channelInfo.totalViews != null && (
                  <span>総視聴回数 {Number(channelInfo.totalViews).toLocaleString()}回</span>
                )}
                {channelInfo.joined && (() => {
                  const d = new Date(channelInfo.joined! * 1000)
                  return <span>登録日 {d.getFullYear()}年{d.getMonth() + 1}月{d.getDate()}日</span>
                })()}
              </div>
              {desc && (
                <p className={`channel-desc${descExpanded ? ' expanded' : ''}`}>{desc}</p>
              )}
              {desc && descNeedsToggle && (
                <button className="channel-desc-toggle" onClick={() => setDescExpanded(e => !e)}>
                  {descExpanded ? '閉じる' : 'もっと見る'}
                </button>
              )}
              {channelInfo.authorId && (
                <button
                  className={`sub-btn${subscribed ? ' subscribed' : ''}`}
                  onClick={handleSubBtn}
                >
                  {subscribed ? (
                    <>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="13" height="13"><polyline points="20 6 9 17 4 12"/></svg>
                      登録済み
                    </>
                  ) : (
                    <>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="13" height="13"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>
                      登録
                    </>
                  )}
                </button>
              )}
            </div>
          </div>
        </div>
      ) : null}

      <div className="channel-tabs-bar">
        <div className="channel-tabs-inner">
          {(['home', 'videos', 'latest', 'shorts', 'streams', 'playlists', 'community', 'search'] as Tab[]).map(tab => {
            const labels: Record<Tab, string> = {
              home: 'ホーム', videos: '動画', latest: '最新', shorts: 'ショート', streams: 'ライブ',
              playlists: 'プレイリスト', community: 'コミュニティ', search: 'チャンネル内検索'
            }
            return (
              <button
                key={tab}
                className={`ch-tab${activeTab === tab ? ' active' : ''}`}
                onClick={() => switchTab(tab)}
              >
                {labels[tab]}
              </button>
            )
          })}
        </div>
      </div>

      <main className="channel-main">
        {activeTab === 'home' && (
          <div className="ch-home">
            {homeLoading ? (
              <div className="ch-home-loading">
                <div className="ch-home-shelf-skeleton">
                  <div className="ch-home-shelf-title-sk" />
                  <div className="ch-home-shelf-row">
                    {Array.from({ length: 4 }).map((_, i) => <SkeletonCard key={i} />)}
                  </div>
                </div>
                <div className="ch-home-shelf-skeleton">
                  <div className="ch-home-shelf-title-sk" />
                  <div className="ch-home-shelf-row">
                    {Array.from({ length: 4 }).map((_, i) => <SkeletonCard key={i} />)}
                  </div>
                </div>
              </div>
            ) : homeError ? (
              <div className="error-state">
                <div className="error-icon">⚠️</div>
                <p>{homeError}</p>
              </div>
            ) : homeData ? (
              <div className="ch-home-content">
                {homeData.featuredVideo && homeData.featuredVideo.videoId && (
                  <div className="ch-home-featured">
                    <div className="ch-home-section-title">注目動画</div>
                    <div className="ch-featured-video">
                      <div className="ch-featured-thumb-wrap">
                        {featuredEduUrl ? (
                          <iframe
                            className="ch-featured-iframe"
                            src={featuredEduUrl}
                            title={homeData.featuredVideo.title}
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowFullScreen
                          />
                        ) : (
                          <SmartImage
                            className="ch-featured-thumb loaded"
                            src={buildVideoThumbnailUrl(homeData.featuredVideo.videoId, 'maxresdefault.jpg')}
                            fallbackSrc={buildVideoThumbnailUrl(homeData.featuredVideo.videoId)}
                            proxyWidth={960}
                            alt={homeData.featuredVideo.title}
                          />
                        )}
                      </div>
                      <div className="ch-featured-info">
                        <Link to={`/watch/${homeData.featuredVideo.videoId}`} className="ch-featured-title-link">
                          <div className="ch-featured-title">{homeData.featuredVideo.title}</div>
                        </Link>
                        <div className="ch-featured-meta">
                          {homeData.featuredVideo.viewCountText && <span>{homeData.featuredVideo.viewCountText}</span>}
                          {homeData.featuredVideo.publishedText && <span>{homeData.featuredVideo.publishedText}</span>}
                        </div>
                        {homeData.featuredVideo.description && (
                          <p className="ch-featured-desc">{homeData.featuredVideo.description}</p>
                        )}
                      </div>
                    </div>
                  </div>
                )}
                {homeData.shelves.map((shelf, si) => (
                  <div key={si} className="ch-home-shelf">
                    {shelf.title && (
                      <div className="ch-home-shelf-header">
                        <div className="ch-home-section-title">{shelf.title}</div>
                        {shelf.items.some(item => item.type === 'video') && (
                          <button className="ch-home-play-all-btn" onClick={() => playAllShelf(shelf)}>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="13" height="13">
                              <polygon points="5,3 19,12 5,21"/>
                            </svg>
                            すべて再生
                          </button>
                        )}
                      </div>
                    )}
                    <div className="ch-home-shelf-scroll">
                      {shelf.items.map((item, ii) => {
                        if (item.type === 'video') {
                          const v = item as HomeVideoItem
                          const thumbSrc = v.thumbnailUrl || buildVideoThumbnailUrl(v.videoId, 'mqdefault.jpg')
                          return (
                            <Link key={ii} to={`/watch/${v.videoId}`} className="ch-home-video-card">
                              <div className="ch-home-card-thumb">
                                <SmartImage
                                  className="ch-home-card-thumb-img"
                                  src={thumbSrc}
                                  fallbackSrc={buildVideoThumbnailUrl(v.videoId)}
                                  proxyWidth={480}
                                  alt={v.title}
                                  loading="lazy"
                                  onLoad={e => (e.currentTarget as HTMLImageElement).classList.add('loaded')}
                                />
                                {v.durationText && <span className="duration-badge">{v.durationText}</span>}
                                {v.isLive && <span className="badge-live" style={{ position: 'absolute', top: 6, left: 6 }}>LIVE</span>}
                              </div>
                              <div className="ch-home-card-info">
                                <div className="ch-home-card-title">{v.title}</div>
                                <div className="ch-home-card-meta">
                                  {v.author && <span>{v.author}</span>}
                                  {v.viewCountText && <span>{v.viewCountText}</span>}
                                  {v.publishedText && <span>{v.publishedText}</span>}
                                </div>
                              </div>
                            </Link>
                          )
                        }
                        if (item.type === 'channel') {
                          const c = item as HomeChannelItem
                          return (
                            <Link key={ii} to={`/channel/${c.channelId}`} className="ch-home-channel-card">
                              <div className="ch-home-channel-avatar-wrap">
                                {c.thumbnailUrl
                                  ? <SmartImage
                                      className="ch-home-channel-avatar"
                                      src={c.thumbnailUrl}
                                      proxyWidth={100}
                                      alt={c.name}
                                      loading="lazy"
                                      onLoad={e => (e.currentTarget as HTMLImageElement).classList.add('loaded')}
                                    />
                                  : <div className="ch-home-channel-avatar-placeholder" />
                                }
                              </div>
                              <div className="ch-home-channel-name">{c.name}</div>
                              {c.subscribers && <div className="ch-home-channel-sub">{c.subscribers}</div>}
                            </Link>
                          )
                        }
                        if (item.type === 'playlist') {
                          const p = item as HomePlaylistItem
                          const thumbSrc = p.thumbnailUrl || ''
                          return (
                            <Link key={ii} to={`/playlist/${p.playlistId}`} className="ch-home-video-card">
                              <div className="ch-home-card-thumb playlist-thumb-wrap">
                                {thumbSrc && (
                                  <SmartImage className="ch-home-card-thumb-img" src={thumbSrc} alt={p.title} loading="lazy" proxyWidth={480}
                                    onLoad={e => (e.currentTarget as HTMLImageElement).classList.add('loaded')} />
                                )}
                                <div className="playlist-count-badge">
                                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="12" height="12">
                                    <line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/>
                                    <line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/>
                                  </svg>
                                  再生リスト
                                </div>
                              </div>
                              <div className="ch-home-card-info">
                                <div className="ch-home-card-title">{p.title}</div>
                              </div>
                            </Link>
                          )
                        }
                        return null
                      })}
                    </div>
                  </div>
                ))}
              </div>
            ) : null}
          </div>
        )}
        {activeTab !== 'home' && (showSort || showSearch) && (
          <div className="tab-controls">
            {showSort && (
              <div className="sort-controls">
                <label className="filter-label">並び順</label>
                <select className="filter-select" value={sortBy} onChange={e => handleSortChange(e.target.value)}>
                  <option value="newest">新しい順</option>
                  <option value="oldest">古い順</option>
                  <option value="popular">人気順</option>
                </select>
              </div>
            )}
            {showSearch && (
              <div className="channel-search-form">
                <form
                  className="ch-search-bar"
                  onSubmit={e => {
                    e.preventDefault()
                    setSearchPage(1)
                    doSearch(searchQuery, 1, true)
                  }}
                >
                  <input
                    type="text"
                    className="search-input"
                    placeholder="チャンネル内を検索..."
                    value={searchQuery}
                    onChange={e => setSearchQuery(e.target.value)}
                    autoComplete="off"
                  />
                  <button type="submit" className="search-btn">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" width="18" height="18">
                      <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
                    </svg>
                  </button>
                </form>
              </div>
            )}
          </div>
        )}

        {activeTab !== 'home' && contentLoading ? (
          <div className="video-grid">
            {Array.from({ length: activeTab === 'playlists' ? 8 : 12 }).map((_, i) => (
              <SkeletonCard key={i} />
            ))}
          </div>
        ) : activeTab !== 'home' && contentError ? (
          <div className="error-state">
            <div className="error-icon">⚠️</div>
            <p>{contentError}</p>
          </div>
        ) : activeTab !== 'home' && noContent ? (
          <div className="empty-state">
            <p>コンテンツがありません</p>
          </div>
        ) : activeTab === 'community' ? (
          <div className="community-area">
            {communityPosts.map((post, i) => (
              <CommunityPostCard key={post.id || i} post={post} />
            ))}
          </div>
        ) : activeTab === 'playlists' ? (
          <div className="video-grid">
            {playlists.map(pl => (
              <PlaylistCard key={pl.playlistId} item={pl} />
            ))}
          </div>
        ) : activeTab !== 'home' ? (
          <div className="video-grid">
            {videos.map(v => (
              <VideoCard key={v.videoId} video={v} />
            ))}
          </div>
        ) : null}

        {activeTab !== 'home' && hasMore && (
          <div className="ch-load-more-wrap">
            <button
              className="ch-load-more"
              disabled={loadingMore}
              onClick={() => {
                if (activeTab === 'search') {
                  const nextPage = searchPage + 1
                  setSearchPage(nextPage)
                  doSearch(searchQuery, nextPage, false)
                } else {
                  loadTab(activeTab, false, sortBy, continuation)
                }
              }}
            >
              {loadingMore ? '読み込み中...' : 'もっと見る'}
            </button>
          </div>
        )}
      </main>
    </div>
  )
}
